local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 10.0 #before 5.0
  publish_frequency: 10.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.025 #increase to for higher res 0.025
  cost_scaling_factor: 0.8
  inflation_radius: 0.25
