# base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_global_planner: "global_planner/GlobalPlanner"
shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 3.0
controller_patience: 6.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 4.0
oscillation_distance: 0.5
