TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.08

  max_vel_theta: 3.0
  min_vel_theta: -3.0

  min_in_place_vel_theta: 2.0

  acc_lim_theta: 1.0
  acc_lim_x: 0.1
  acc_lim_y: 0.0

  holonomic_robot: false

  sim_time: 2.0
  escape_vel: -0.2

  meter_scoring: false
  heading_scoring: false

  pdist_scale: 1.8
  gdist_scale: 0.5
  occdist_scale: 0.08

  publish_cost_grid_pc: false
  global_frame_id: odom
