controller_list:
  - name: fake_arm_group_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_group_controller
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: arm_group
    pose: all_zeros
  - group: gripper_group
    pose: full_open